# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ex' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ex
  #pod 'RedpacketLib',:path => "../"
  pod 'AlipayTest',:path => "../../alipayTest"
  pod 'RedpacketLib',:path => "../../RedpacketLib"
end
